version: 2
updates:
   - package-ecosystem: "npm"
     directory: "/"
     schedule:
         interval: 'weekly'
         day: "friday"
         time: '00:00'
         timezone: 'America/New_York'
     target-branch: "master"
     labels:
        - "dependencies"
     assignees:
        - "jagcruz"
     reviewers:
        - "jagcruz"
     
